---
name: CI/CD Pipeline

on:
  push:
    branches: [master]
  pull_request:
    branches: ['**']

permissions:
      contents: read
      packages: write
      statuses: write

concurrency:
  group: main-${{ github.ref }}
  cancel-in-progress: true

jobs:
  tag-release:
    uses: ./.github/workflows/tag.yml
    secrets:
      PERSONAL_TOKEN: ${{ secrets.PERSONEL_TOKEN }}
